### ISSUE TITLE
requirements error

### ISSUE THREAD

**Issue by ghost3666** [DavidMGilbert/btc-hack-offline#10]
pip3 install -r requirements.txt
Requirement already satisfied: base58 in c:\users\\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: ecdsa in c:\users\\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 2)) (0.18.0)
Requirement already satisfied: requests in c:\users\\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 3)) (2.31.0)
Collecting multiprocessing (from -r requirements.txt (line 4))
  Using cached multiprocessing-2.6.2.1.tar.gz (108 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\\AppData\Local\Temp\pip-install-g33o6v0d\multiprocessing_409eb2d5e92149ca9a2c65708db60885\setup.py", line 94
          print 'Macros:'
          ^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by HustlazHub** [comment]
I'm having the exact same issue - have U found a solution by chance @ghost3666 ??? 

@DavidMGilbert  please help

**Comment by tomdevdar** [comment]
Any solucion? have the same issue : /
